### ISSUE TITLE
Move to VuePress

### ISSUE THREAD

**Issue by clarkeash** [laravel-validation-rules/laravel-validation-rules.github.io#9]
What are your thoughts on moving to [VuePress](https://vuepress.vuejs.org/)?

I quickly threw a demo together (I will put more work into it if you are interested)

Screenshots:

Home:
<img width="1392" alt="screen shot 2018-08-02 at 21 47 23" src="https://user-images.githubusercontent.com/1612186/43607162-b80bae92-969d-11e8-8db3-5534322488a8.png">

Contributing:
<img width="1392" alt="screen shot 2018-08-02 at 21 47 30" src="https://user-images.githubusercontent.com/1612186/43607161-b7f1c874-969d-11e8-8df4-1c3cd5b1b5ca.png">

A Rule:
<img width="1392" alt="screen shot 2018-08-02 at 21 47 33" src="https://user-images.githubusercontent.com/1612186/43607160-b7d9710c-969d-11e8-9850-81366d95937d.png">

If you like it then I am happy to put more work into this.

**Comment by ssx** [comment]
More than happy to switch over Ash, great work! 👍 Get as much as you want to initially and we'll get it switched over.

**Comment by clarkeash** [comment]
closing. refer to #10
